version: '3.6'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: prindustry
    ports:
      - 27017:27017
    volumes:
      - docker-data:/data/db
    networks:
      - mongodb_net

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    restart: always
    depends_on:
        - mongodb
    ports:
      - 80:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: prindustry
    networks:
      - mongodb_net

volumes:
  docker-data:
    name: users-mogoDB-data

networks:
  mongodb_net:
    driver: bridge
